### ISSUE TITLE
gulp-handlebars error on fresh install

### ISSUE THREAD

**Issue by danpaulsmith** [sim51/tank-browser#3]
```
[tank-browser] gulp build                                                        master
module.js:338
    throw err;
          ^
Error: Cannot find module 'gulp-handlebars'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/dansmith/Sites/tank-browser/gulpfile.js:13:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
[tank-browser]                                                                   master
```

**Comment by danpaulsmith** [comment]
Actually I manually installed it and it's fine now. Not sure why npm install didn't install gulp-handlebars...

**Comment by danpaulsmith** [comment]
Closed
